### ISSUE TITLE
What is the rationale behind LDRSHI in the ARM decoder?

### ISSUE THREAD

**Issue by alirazeen** [beehive-lab/pie#1]
The ARM decoder table has entries for LDRSH and LDRSHI:

```
ldrsh            aaaa000p ubw1cccc ddddeeee 1111ffff, a:auto_cond, b:immediate, d:rd, c:rn, f:rm, e:imm4h, u:updown, w:writeback
ldrshi           aaaa000b c1d1eeee ffffgggg 1111hhhh, a:auto_cond, f:rd, e:rn, h:rm, g:imm4h, b:prepostindex, c:updown, d:writeback
```

As far as I can tell, the only difference between the two is that LDRSHI is the immediate variant of LDRSH. But since one can read the immediate field (`b`) in LDRSH, why is there a need for LDRSHI?

On a related note, i believe the `hhhh` bits in LDRSHI should be `imm4L`instead of `rm`.

Edit: After posting this issue, I noticed that the LDRSH entry is missing the `p:prepostindex` entry.

**Comment by lgeek** [comment]
Thanks for reporting this. 
LDRSHI with its `rm` field is a leftover from back when PIE used a hierarchical structure to define instructions. For consistency with the other LDRS* instructions, I'll remove it. I'll also define the `p` field for ldrsh.

**Comment by alirazeen** [comment]
Ah, I see. Thanks for the explanation. I really like the current design of the decoder.
