### ISSUE TITLE
Potential bug: THUMB_STMFD16 should be THUMB_STMEA16

### ISSUE THREAD

**Issue by alirazeen** [beehive-lab/pie#3]
The Thumb table has the following entry for `stmfd16`:

```
stmfd16          11000aaa bbbbbbbb, a:rn, b:reglist
```

The bit pattern `11000` corresponds to STMEA16.

**Comment by lgeek** [comment]
Thanks for reminding me about this. It's a known issue (and there's a note in the MAMBO Thumb scanner), but I need to coordinate renaming it over a larger number of repositories and branches. Will do. 

In fact there's no 16-bit STMFD.
